---
---
title: "sim"
author: Report by Rich Evans
date: 2023
output: 
  html_document:
     number_sections: true


---

This is a simple two group simulation for PU data. 

There are two groups, called case and control

The idea is to get some idea of how sample size, group imbalance, and non-detection affects statistical decisions via p-values.

```{r,include=FALSE}
#install.packages("pacman")
pacman::p_load(
       data.table, # to group and clean data
       tidyverse,  # allows use of pipe (%>%) function in this chapter
       janitor,     #for clean_names and tabyl
       broom,   #tidy output, use tidy(xxx)
       gtsummary,  #nice tables
       magrittr, # for %<>%
       effectsize,
       rstatix,
        kableExtra
   ) 
```




```{r,include=FALSE}

sim.fun<-function(num.iter = NULL
                  ,n.cases = NULL    
                  ,n.controls.unlabeled = NULL          
                  ,prop.nondetect = NULL
                  ,trt.eff = NULL,...){
out1 <- NULL
out2 <- NULL
out3 <- NULL

n.nondetect <- round(prop.nondetect*n.controls.unlabeled)

for (i in 1:num.iter){
df <- data.frame(
real.labels = c(rep(1,(n.cases+n.nondetect))
                 ,rep(0,(n.controls.unlabeled-n.nondetect))),
labelz = c(rep(1,n.cases),rep(0,n.controls.unlabeled)),
dat = c(rnorm(n.cases+n.nondetect,mean=trt.eff)
        ,rnorm((n.controls.unlabeled-n.nondetect)
                       ,mean = 0)))

#pu
out1 <- c(out1,wilcox_test(data=df,dat ~ labelz)$p)

#tru
out2 <- c(out2,wilcox_test(data=df,dat ~ real.labels)$p)



}

#agree less than 0.05?
#2=agree, both less than 0.05; 1=disgree, one of them is less; 0=agree both are above agree

out3<-(out1<0.05) + (out2<0.05) 
out4<-1-(out3==1) #out3==1 is disagree, 1- == agree
out5 <- as.integer(out3==2) #agree and statistically signif.

return(list(n.cases=n.cases,
                  n.controls.unlabeled=n.controls.unlabeled,
                  n.case.tru = (n.cases+n.nondetect),
                  n.cntl.tru=(n.controls.unlabeled-n.nondetect),
                  n.nondetect=n.nondetect,
                  trt.eff=trt.eff,
                  prop.nondetect=prop.nondetect,
                  pu=out1,
                  tru=out2,
                  p.agree = out4,
                  both.sig= out5))
}


                    
```





```{r}
 now<-Sys.time()

###this parmlist has a very small effect size, which isn't interesting
 
#  parmlist<-list(
# c(rep(500,32)),             #interations; num.iter
# c(120,60,80,90,120,60,80,90,120,60,80,90,120,60,80,90,120,60,80,90,120,60,80,90,120,60,80,90,120,60,80,90),  #cases; n.cases
# c(60,120,80,90,60,120,80,90,60,120,80,90,60,120,80,90,60,120,80,90,60,120,80,90,60,120,80,90,60,120,80,90),  #controls unlabeled
# c(rep(0.1,8),rep(0.05,8),rep(0.15,8),rep(0.01,8)),  #non-detection proportion
# c(0.38,0.38,0.38,.38,0.1,0.1,0.1,0.1,0.38,0.38,0.38,0.38,0.1,0.1,0.1,0.1,0.38,0.38,0.38,.38,0.1,0.1,0.1,0.1,0.38,0.38,0.38,0.38,0.1,0.1,0.1,0.1) #treat effect
#  )
 
#   parmlist<-list(
# c(rep(3000,16)),             #interations; num.iter
# c(120,60,80,90,120,60,80,90,120,60,80,90,120,60,80,90),  #cases; n.cases
# c(60,120,80,90,60,120,80,90,60,120,80,90,60,120,80,90),  #controls unlabeled
# c(rep(0.1,4),rep(0.05,4),rep(0.15,4),rep(0.01,4)),  #non-detection proportion
# c(rep(0.38,16)) #treat effect
#  )

 parmlist<-list(
c(rep(3000,12)),             #interations; num.iter
rep(c(120,80,100),4),  #cases; n.cases
rep(c(80,120,100),4),  #controls unlabeled
c(rep(0.1,12)), #non-detection proportion
c(rep(0.4,3),rep(.1,3),rep(.9,3),rep(1.8,3)) #treat effect
 )
 
  
# ##This is to see if balance matters
#  parmlist<-list(
# c(rep(3000,5)),             #interations; num.iter
# c(rep(80,5)),  #cases; n.cases
# c(120,110,100,90,80),  #controls unlabeled
# c(rep(0.1,5)),  #non-detection proportion
# c(rep(0.4,5)) #treat effect
#  )


 
#####  #sample size matters more than direction of error
#   parmlist<-list(
# c(rep(500,6)),             #interations; num.iter
# c(120,120,120,60,70,80),  #cases; n.cases
# c(60,70,80,120,120,120),  #controls unlabeled
# c(.05,.05,0.05,.05,.05,0.05),  #non-detection proportion
# c(rep(.38,6)) #treat effect
#  )
 
foo<-pmap(parmlist,sim.fun)


goo <- bind_rows(foo, .id = "column_label")  #unlists and binds rows


zoo1 <- goo %>% group_by(n.cases
                        ,n.controls.unlabeled
                        ,trt.eff
                        ,prop.nondetect) %>% 
  dplyr::summarise(n.nodetec=mean(n.nondetect)
                   ,p.agree=mean(p.agree)
                   ,both.sig=mean(both.sig)
                   ,p.tru=mean(tru)
                   )


zoo1 %>% ungroup() %>% arrange(desc(both.sig)) %>% select(-p.agree) %>% 
  kable(caption = "both.sig") %>% kable_styling(full_width = FALSE) %>% kable_classic()

zoo1 %>% ungroup() %>% arrange(desc(p.agree)) %>%
  kable(caption = "p.agree ") %>% kable_styling(full_width = FALSE)%>% kable_classic()

 

oddsratio_to_d(2,log=FALSE) #this coverts OR to cohens so that I make this like SNPs data
d_to_oddsratio(.1)
oddsratio_to_d(1.2,log=FALSE)
print(difftime(Sys.time(),now,units="mins"))
 
```



