---
title: "sim"
author: Report by Rich Evans
date: 2023
output:
    html_document


---

This is a simple two group simulation for PU data. 

There are two groups, called case and control

The idea is to get some idea of how sample size, group imbalance, and non-detection affects statistical decisions via p-values.

```{r,include=FALSE}
#install.packages("pacman")
pacman::p_load(
       data.table, # to group and clean data
       tidyverse,  # allows use of pipe (%>%) function in this chapter
       janitor,     #for clean_names and tabyl
       broom,   #tidy output, use tidy(xxx)
       gtsummary,  #nice tables
       magrittr, # for %<>%
       effectsize,
       rstatix,
       pander, #to write tables as simple text for cut-and-paste
       knitr,
        kableExtra
   ) 
```




```{r,include=FALSE}

sim.fun<-function(num.iter = NULL
                  ,test=NULL
                  ,n.cases = NULL    
                  ,n.unl.cntr = NULL          
                  ,prp.nondet = NULL
                  ,t.eff = NULL,...){
out1 <- NULL
out2 <- NULL
out3 <- NULL

n.nondet <- round(prp.nondet*n.unl.cntr)

for (i in 1:num.iter){
df <- data.frame(
real.labels = c(rep(1,(n.cases+n.nondet))
                 ,rep(0,(n.unl.cntr-n.nondet))),
labelz = c(rep(1,n.cases),rep(0,n.unl.cntr)),
dat = c(rnorm(n.cases+n.nondet,mean=t.eff)
        ,rnorm((n.unl.cntr-n.nondet)
                       ,mean = 0)))

##--------------welsh's option
if (test=="w"){
#pu
out1 <- c(out1,t_test(data=df,dat ~ labelz,var.equal=FALSE)$p)

#tru
out2 <- c(out2,t_test(data=df,dat ~ real.labels,var.equal=FALSE)$p)
}

##-----------non para option--------------------
if (test=="t"){
#pu
out1 <- c(out1,wilcox_test(data=df,dat ~ labelz)$p)

#tru
out2 <- c(out2,wilcox_test(data=df,dat ~ real.labels)$p)
}
}

#agree less than 0.05?
#2=agree, both less than 0.05; 1=disgree, one of them is less; 0=agree both are above agree

return(list(n.cases=n.cases,
                  n.unl.ctrl=n.unl.cntr,
                  n.case.tru = (n.cases+n.nondet),
                  n.cntl.tru=(n.unl.cntr-n.nondet),
                  n.nondet=n.nondet,
                  t.eff=t.eff,
                  prp.nondet=prp.nondet,
                  pu=out1,
                  tru=out2))
}


                    
```





```{r,results='asis'}


sim.table<-function(parmlist){
 
  now<-Sys.time()
  
foo<-pmap(parmlist,sim.fun)


goo <- bind_rows(foo, .id = "column_label")  #unlists and binds rows


zoo1 <- goo %>% group_by(n.cases
                        ,n.unl.ctrl
                        ,t.eff
                        ,prp.nondet) %>% 
  dplyr::summarise(n.nodetec=mean(n.nondet)
                   ,pu.minus.tru=mean(pu-tru)
                   ,pu.less.tru=mean(pu<mean(tru))
                   ,p.tru=mean(tru)
                   ,p.pu=mean(pu)
                   )

print(difftime(Sys.time(),now,units="mins"))
return(pandoc.table(zoo1 %>% ungroup() %>% arrange(p.pu)
                    ,style='rmarkdown',digits=3,split.table=Inf))

}


oddsratio_to_d(2,log=FALSE) #this coverts OR to cohens so that I make this like SNPs data
d_to_oddsratio(.1)
oddsratio_to_d(1.2,log=FALSE)

 
```
<!-- https://cran.r-project.org/web/packages/pander/vignettes/pandoc_table.html -->

```{r, results='asis',message=FALSE}
###this checlks different patterns for the same sample size
 now<-Sys.time()

print("different patterns for the same sample size")
 parmlist<-list(
c(rep(5555,3)),             #interations; num.iter
c("t","t","t"),
c(120,80,100),  #cases; n.cases
c(80,120,100),  #controls unlabeled
c(rep(0.01,3)), #non-detection proportion
c(rep(0.4,3)) #treat effect
 )


sim.table(parmlist=parmlist)

print("different patterns for the same sample size")
 parmlist<-list(
c(rep(5555,3)),             #interations; num.iter
c("t","t","t"),
c(120,80,100),  #cases; n.cases
c(80,120,100),  #controls unlabeled
c(rep(0.05,3)), #non-detection proportion
c(rep(0.4,3)) #treat effect
 )


sim.table(parmlist=parmlist)

print("different patterns for the same sample size")
 parmlist<-list(
c(rep(5555,3)),             #interations; num.iter
c("t","t","t"),
c(120,80,100),  #cases; n.cases
c(80,120,100),  #controls unlabeled
c(rep(0.1,3)), #non-detection proportion
c(rep(0.4,3)) #treat effect
 )


sim.table(parmlist=parmlist)

print("decreased treatment effect different patterns for the same sample size")

 parmlist<-list(
c(rep(5555,3)),             #interations; num.iter
c("t","t","t"),
c(120,80,100),  #cases; n.cases
c(80,120,100),  #controls unlabeled
c(rep(0.1,3)), #non-detection proportion
c(rep(0.1,3)) #treat effect
 )

sim.table(parmlist=parmlist)

print("increased treatment effect different patterns for the same sample size")
parmlist<-list(
c(rep(5555,3)),             #interations; num.iter
c("t","t","t"),
c(120,80,100),  #cases; n.cases
c(80,120,100),  #controls unlabeled
c(rep(0.1,3)), #non-detection proportion
c(rep(1,3)) #treat effect
 )

sim.table(parmlist=parmlist)


print("different sample sizes to assess balance vs unbalanced")
parmlist<-list(
c(rep(5555,5)),             #interations; num.ite
c("t","t","t"),
c(120,80,95,175,25),  #cases; n.cases
c(80,120,95,25,175),  #controls unlabeled
c(rep(0.1,5)), #non-detection proportion
c(rep(.35,5)) #treat effect
 )

sim.table(parmlist=parmlist)

print("different designs")
 parmlist<-list(
c(rep(5555,3)),             #interations; num.iter
c("t","t","t"),
c(120,80,100),  #cases; n.cases
c(80,120,100),  #controls unlabeled
c(rep(0.1,3)), #non-detection proportion
c(rep(0.4,3)) #treat effect
 )


sim.table(parmlist=parmlist)


print("cut some cases???")
 parmlist<-list(
c(rep(5555,4)),             #interations; num.iter
c("t","t","t","t"),
c(175,25,25,150),  #cases; n.cases
c(25,175,150,25),  #controls unlabeled
c(rep(0.1,4)), #non-detection proportion
c(rep(0.4,4)) #treat effect
 )


sim.table(parmlist=parmlist)


print("sample sizes from the papers: healey (216), innes (217), conz (334), baker (392)")
 parmlist<-list(
c(rep(5555,4)),             #interations; num.iter
c(rep("t",4)),      #wilcoxon tests="w", welsh="t"
c(161,91,191,151),  #cases; n.cases
c(55,126,143,241),  #controls unlabeled
c(rep(0.1,4)), #non-detection proportion
c(rep(0.4,4)) #treat effect
 )


sim.table(parmlist=parmlist)


print("sample sizes from the papers: healey (216), innes (217), conz (334), baker (392)")
 parmlist<-list(
c(rep(5555,4)),             #interations; num.iter
c(rep("w",4)),      #wilcoxon tests="w", welsh="t"
c(161,91,141,121),  #cases; n.cases
c(55,126,75,95),  #controls unlabeled
c(rep(0.1,4)), #non-detection proportion
c(rep(0.4,4)) #treat effect
 )


sim.table(parmlist=parmlist)

print(difftime(Sys.time(),now,units="mins"))

```

