---
title: "sim"
author: Report by Rich Evans
date: 2023
output:
    html_document


---

This is for power over different nondetection rates for balanced and unbalanced sample sizes

```{r,include=FALSE}
# install.packages("pacman")
pacman::p_load(
    data.table, # to group and clean data
    tidyverse, # allows use of pipe (%>%) function in this chapter
    janitor, # for clean_names and tabyl
    broom, # tidy output, use tidy(xxx)
    gtsummary, # nice tables
    magrittr, # for %<>%
    effectsize,
    pROC,
    rstatix,
    pwr, # power calculations
    pander, # to write tables as simple text for cut-and-paste
    knitr,
    rcompanion, # for cohen's w
    kableExtra,
    bindata,
    here
)

here::i_am("README.md")
```

this version samples from a binomial
```{r,include=FALSE}
sim.fun <- function(
    num.iter = NULL,
    n.cases = NULL,
    n.naiv.control = NULL,
    eff.sz = NULL,
    prp.nondet = NULL, ...) {
    out1 <- NULL
    out2 <- NULL
    out3 <- NULL
    out4 <- NULL

    ### numbers of things
    n.dogs <- n.cases + n.naiv.control # total number of dogs


    # control group is made up of the unlabeled pos and the real unaffected
    # number of positive dogs who are unlabled
    unlab.pos <- round(n.naiv.control * prp.nondet)
    n.tru.unaff <- n.naiv.control - unlab.pos # the number of unaffected

    n.tru.aff <- n.cases + unlab.pos # the number of positive dogs in both groups

    tru.labels <- c(rep(1, n.tru.aff), rep(0, (n.dogs - n.tru.aff)))
    naive.labels <- c(rep(1, n.cases), rep(0, n.naiv.control))



    for (i in 1:num.iter) {
        ### sample X
        # this is where the stocastic part comes in

        x.real.affected <- rbinom(n.cases, 1, eff.sz + .2) #0.2 is the background disease prevalence

# eff.sz is the probability above baseline of being affected without the snp
# the binomials determine who is affected.
# Pan would have determined "prob" from a logistic formula
# where the covariate is the snp and the snp comes from a latent MVN.
# For Pan, it would be sample a MVN, use a cutoff to determine mutation, then
# use mutation (0,1,2) with the OR parameter and baseline rate to calc "prob"
# in the usual formula 1/1+exp(-baseline-or*snp))

        x.real.control <- c(
            rbinom(unlab.pos, 1, prob = eff.sz + .2),   #0.2 is the background disease prevalence
            rbinom(n.tru.unaff, 1, prob = 0.2)
        )

        naive_X <- c(x.real.affected, x.real.control) #observed disease status
    

    
        naive.dat <- data.frame(
            X = naive_X,
            y = naive.labels
        )

         temp.out1 <- as.numeric(rcompanion::cohenW(naive.dat$y, naive.dat$X)) # cohen_w
        out1 <- c(out1, temp.out1)

         temp.out4 <-  temp.out4 <- fisher.test(naive.dat$X,naive.dat$y)$p.value<0.05
         out4 <- c(out4, temp.out4)

        #save the odds ratio for the naive model
        junk <- table(naive.dat$y, naive.dat$X)
        out2 <- c(out2, (junk[1, 1] * junk[2, 2]) / (junk[2, 1] * junk[1, 2]))

        #save the odds ratio for the real model
        junk <- table(tru.labels, naive.dat$X)
        out3 <- c(out3, (junk[1, 1] * junk[2, 2]) / (junk[2, 1] * junk[1, 2]))

    } # loop

    return(list(
        n.cases = n.cases,
        n.naiv.control = n.naiv.control,
        prp.nondet = prp.nondet,
        eff.sz = eff.sz,
        naive.pwr = out4,
        cohen = out1,
        naive_or = out2,
        tru_or = out3
    ))
}
```


Run three at a time-makes all the data for the plot
```{r}
now <- Sys.time()


parmlist <- list(
    rep(5001, 3), # interations; num.iter
    c(100, 110, 120), # n.cases
    c(100, 110, 120), # number unlabeled
    rep(.21, 3), # eff.sz 
    c(0, 0.1, 0.1) #nondetection rate
) # non-detection proportion

big.otpt_100_100 <- bind_rows(pmap(parmlist, sim.fun),
    .id = "column_label"
) # unlists and binds rows

smry.otpt_100_100 <- big.otpt_100_100 %>%
    group_by(n.cases, n.naiv.control, prp.nondet, eff.sz) %>%
    dplyr::summarise(
        prp.nondet = mean(prp.nondet),
        eff.sz = mean(eff.sz),
        naive.power = mean(naive.pwr),
        cohen = mean(cohen),
        naive_or = mean(naive_or),
        tru_or = mean(tru_or)
    )


parmlist <- list(
    rep(5001, 3), # interations; num.iter
    c(150, 165, 180), # n.cases
    c(50, 55, 60), # number unlabeled
    rep(.21, 3), # eff.sz for 
    c(0, 0.1, 0.1) #nondetection rate
) 


big.otpt_150_50 <- bind_rows(pmap(parmlist, sim.fun),
    .id = "column_label"
) # unlists and binds rows

smry.otpt_150_50 <- big.otpt_150_50 %>%
    group_by(n.cases, n.naiv.control, prp.nondet, eff.sz) %>%
    dplyr::summarise(
        prp.nondet = mean(prp.nondet),
        eff.sz = mean(eff.sz),
        naive.power = mean(naive.pwr),
        cohen = mean(cohen),
        naive_or = mean(naive_or),
        tru_or = mean(tru_or)
    )



parmlist <- list(
    rep(5001, 3), # interations; num.iter
    c(50, 55, 60), 
    c(150, 165, 180), 
    rep(.21, 3), # eff.sz for 
    c(0, 0.1, 0.1) #nondetection rate
) 


big.otpt_50_150 <- bind_rows(pmap(parmlist, sim.fun),
    .id = "column_label"
) # unlists and binds rows



smry.otpt_50_150 <- big.otpt_50_150 %>%
    group_by(n.cases, n.naiv.control, prp.nondet, eff.sz) %>%
    dplyr::summarise(
        prp.nondet = mean(prp.nondet),
        eff.sz = mean(eff.sz),
        naive.power = mean(naive.pwr),
        cohen = mean(cohen),
        naive_or = mean(naive_or),
        tru_or = mean(tru_or)
    )


#test git
pandoc.table(smry.otpt_100_100 %>% ungroup() %>% arrange(prp.nondet),
    style = "rmarkdown", digits = 3, split.table = Inf
)

pandoc.table(smry.otpt_150_50 %>% ungroup() %>% arrange(prp.nondet),
    style = "rmarkdown", digits = 3, split.table = Inf
)

pandoc.table(smry.otpt_50_150 %>% ungroup() %>% arrange(prp.nondet),
    style = "rmarkdown", digits = 3, split.table = Inf
)



difftime(Sys.time(), now)
```

This is to make tables for the long abstract
```{r, echo=FALSE}

# the reference mean 
mn_100_100 <- as.numeric(smry.otpt_100_100 %>%
    ungroup() %>%
    select(prp.nondet, naive.power) %>%
    reframe(mean(naive.power[prp.nondet == 0])))

## save this table to read into the paper

.bigtable<-rbind(
smry.otpt_100_100 %>%
    ungroup() %>%
    select(n.cases, n.naiv.control, prp.nondet, naive.power) %>%
    reframe(
            pos = n.cases,
            controls = n.naiv.control,
            prp.nondet = prp.nondet,
            rel.loss = 100 * (naive.power - mn_100_100) / mn_100_100,
            abs.loss = (naive.power - mn_100_100)
            ),


smry.otpt_150_50 %>%
    ungroup() %>%
    select(n.cases, n.naiv.control, prp.nondet, naive.power) %>%
    reframe(
            pos = n.cases,
            controls = n.naiv.control,
        prp.nondet = prp.nondet,
    rel.loss = 100 * (naive.power - mn_100_100) / mn_100_100,
    abs.loss = (naive.power - mn_100_100)),


smry.otpt_50_150 %>%
    ungroup() %>%
    select(n.cases, n.naiv.control, prp.nondet, naive.power) %>%
    reframe(
            pos = n.cases,
            controls = n.naiv.control,
        prp.nondet = prp.nondet,
    rel.loss = 100 * (naive.power - mn_100_100) / mn_100_100,
    abs.loss = (naive.power - mn_100_100))
) |> arrange(desc(rel.loss))

write.csv(.bigtable,file=here("data","derived","bigtable_inc_ss.csv"))

```

usually use this one
The plot below is power loss normlize to the best power, which is 
balance groups (100,100) and 0 prp.nondet.
```{r, echo=FALSE}
df.plot1 <- smry.otpt_100_100 %>%
    ungroup() %>%
    select(n.cases, n.naiv.control, prp.nondet, naive.power) %>%
    reframe(prp.nondet = prp.nondet, zzz = naive.power /
        mean(naive.power[prp.nondet == 0])) %>%
    mutate(aaa = "1", prp.nondet = prp.nondet * 100, zzz = (zzz * 100) - 100)


mn_100_100 <- as.numeric(smry.otpt_100_100 %>%
    ungroup() %>%
    select(prp.nondet, naive.power) %>%
    reframe(mean(naive.power[prp.nondet == 0])))

df.plot2 <- smry.otpt_150_50 %>%
    ungroup() %>%
    select(n.cases, n.naiv.control, prp.nondet, naive.power) %>%
    reframe(prp.nondet = prp.nondet, zzz = naive.power / mn_100_100) %>%
    mutate(aaa = "2", prp.nondet = prp.nondet * 100, zzz = (zzz * 100) - 100)

df.plot3 <- smry.otpt_50_150 %>%
    ungroup() %>%
    select(n.cases, n.naiv.control, prp.nondet, naive.power) %>%
    reframe(prp.nondet = prp.nondet, zzz = naive.power / mn_100_100) %>%
    mutate(aaa = "3", prp.nondet = prp.nondet * 100, zzz = (zzz * 100) - 100)

df.plot <- bind_rows(df.plot1, df.plot2, df.plot3)

tiff("increase_ss_all_three_80percentb.tiff", units = "in", width = 7, height = 4, res = 600)

ggplot(data = df.plot, aes(x = prp.nondet, zzz, color = aaa)) +
    geom_smooth() +
    xlab("Percent undetected postitives in the control group") +
    ylab("Percent power loss") +
    labs(
        title = "Percent power loss from positive cases in the GWAS control group",
        subtitle = "Relative to reference power: 100 cases, 100 controls with no undetected positives",
        caption = "Reference power = 0.82, alpha = 0.05",
        color = "Naive sample sizes"
    ) +
    theme(
        plot.title = element_text(size = 14), # Center title position and size
        plot.subtitle = element_text(size = 10), # Center subtitle
        plot.caption = element_text(face = "italic") # move caption to the left
    ) +
    scale_color_discrete(labels = c("100 cases, 100 controls", "150 cases, 50 controls", "50 cases, 150 controls"))


dev.off()
```
```